import "Windows.Foundation.idl";

namespace test_component
{
    runtimeclass ArrayMethods
    {
        static String InInt32Array(Int32[] value);
        static String InStringArray(String[] value);
        static String InObjectArray(Object[] value);
        static String InStringableArray(Windows.Foundation.IStringable[] value);
        static String InStructArray(BlittableStruct[] value);
        static String InNonBlittableStructArray(NonBlittableStruct[] value);
        static String InEnumArray(Signed[] value);

        static void OutInt32Array(out Int32[] value);
        static void OutStringArray(out String[] value);
        static void OutObjectArray(out Object[] value);
        static void OutStringableArray(out Windows.Foundation.IStringable[] value);
        static void OutStructArray(out BlittableStruct[] value);
        static void OutNonBlittableStructArray(out NonBlittableStruct[] value);
        static void OutEnumArray(out Signed[] value);

        static void RefInt32Array(ref Int32[] value);
        static void RefStringArray(ref String[] value);
        static void RefObjectArray(ref Object[] value);
        static void RefStringableArray(ref Windows.Foundation.IStringable[] value);
        static void RefStructArray(ref BlittableStruct[] value);
        static void RefNonBlittableStructArray(ref NonBlittableStruct[] value);
        static void RefEnumArray(ref Signed[] value);

        static Int32[] ReturnInt32Array();
        static String[] ReturnStringArray();
        static Object[] ReturnObjectArray();
        static Windows.Foundation.IStringable[] ReturnStringableArray();
        static BlittableStruct[] ReturnStructArray();
        static NonBlittableStruct[] ReturnNonBlittableStructArray();
        static Signed[] ReturnEnumArray();
    }
}