import "Windows.Foundation.idl";

namespace test_component
{
    interface InterfaceWithReturnDelegate
    {
        event test_component.Delegates.ReturnInt32Delegate EventWithReturn;
    };
    runtimeclass EventTester
    {
        EventTester(IIAmImplementable impl);

        void Subscribe();
        void Unsubscribe();
        String GetResult();
        Int32 Count { get; };
    }
}