import "Windows.Foundation.idl";

// this is a list of swift keywords which are valid midl and c++ names
// the goal is just to get this to compile. We use standard WinRT naming
// scheme here so that they pass MIDL/C++ compilations
namespace test_component
{
    enum Keywords
    {
        As,
        Break,
        Case,
        Catch,
        Class,
        Continue,
        Default,
        Defer,
        Do,
        Else,
        Enum,
        Extension,
        Fallthrough,
        False,
        For,
        Func,
        If,
        Import,
        In,
        Internal,
        Is,
        Let,
        Nil,
        Private,
        Protocol,
        Public,
        Repeat,
        Rethrows,
        Return,
        Self,
        Static,
        Struct,
        Super,
        Switch,
        Throw,
        Throws,
        True,
        Try,
        Var,
        Where,
        While
    };

    interface WithKeyword {
        void Enum(String extension);
        String Struct;
        event Windows.Foundation.EventHandler<Object> Repeat;
    }
}