inputs:
  config:
    required: true
    type: string
  GITHUB_TOKEN:
    required: true

runs:
  using: "composite"

  steps:
  - name: Configure VC++ build for amd64
    uses: compnerd/gha-setup-vsdevenv@f1ba60d553a3216ce1b89abe0201213536bc7557 # main as of 2024-11-12
    with:
      arch: amd64
      winsdk: "10.0.22621.0" # GitHub runners have 10.0.26100.0 which regresses Swift's ucrt module

  - name: Install Swift
    uses: compnerd/gha-setup-swift@b6c5fc1ed5b5439ada8e7661985acb09ad8c3ba2 # main as of 2024-11-12
      with:
        branch: swift-6.0-release
        tag: 6.0-RELEASE

  - name: Configure CMake
    shell: cmd
    run: cmake --preset ${{ inputs.config }}

  - name: Build
    shell: cmd
    run: |
      cmake --build --preset ${{ inputs.config }}
      cmake --build --preset ${{ inputs.config }} --target install

 # Right now this is failing due to line-ending differences, need to figure out how to fix that
 # - name: Validate Checked-In Files are Up-To-Date
 #   shell: powershell
 #   run: |
 #     $dirty = git status --porcelain
 #     if ($dirty) {
 #       git diff
 #       throw "Checked in files are not up-to-date, re-run swiftwinrt before checking-in: \n$dirty"
 #     }

  - name: Upload swiftwinrt logs on failure
    uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3
    if: failure()
    with:
      name: swiftwinrt-log
      path: ${{ github.workspace }}\tests\test_component\swiftwinrt.log

  - name: Run test app
    shell: cmd
    run: .\out\${{ inputs.config }}\bin\test_app.exe
