// WARNING: Please don't edit this file. It was generated by Swift/WinRT v0.0.1
// swiftlint:disable all
import Foundation
import CWinRT

/// [Open Microsoft documentation](https://learn.microsoft.com/uwp/api/windows.foundation.iasyncoperationwithprogress-2)
public protocol IAsyncOperationWithProgress<TResult,TProgress> : IAsyncInfo {
    associatedtype TResult
    associatedtype TProgress
    /// [Open Microsoft documentation](https://learn.microsoft.com/uwp/api/windows.foundation.iasyncoperationwithprogress-2.getresults)
    func getResults() throws -> TResult
    /// [Open Microsoft documentation](https://learn.microsoft.com/uwp/api/windows.foundation.iasyncoperationwithprogress-2.progress)
    var progress: WindowsFoundation.AsyncOperationProgressHandler<TResult, TProgress>? { get set }
    /// [Open Microsoft documentation](https://learn.microsoft.com/uwp/api/windows.foundation.iasyncoperationwithprogress-2.completed)
    var completed: WindowsFoundation.AsyncOperationWithProgressCompletedHandler<TResult, TProgress>? { get set }
}

public typealias AnyIAsyncOperationWithProgress<TResult,TProgress> = any IAsyncOperationWithProgress<TResult,TProgress>

public extension IAsyncOperationWithProgress {
    func get() async throws -> TResult {
        if status == .started {
            let event = WaitableEvent()
            completed = { _, _ in
                Task { await event.signal() }
            }
            await event.wait()
        }
        return try getResults()
    }
}

// MARK: - IAsyncOperationWithProgress Internals

@_spi(WinRTInternal)
extension __IMPL_Windows_Foundation {
}
@_spi(WinRTInternal)
extension __ABI_Windows_Foundation {
    private static let IID___x_ABI_C__FIAsyncOperationWithProgress_2_TResult_TProgress: WindowsFoundation.IID = .init(
        Data1: 0xB5D036D7, Data2: 0xE297, Data3: 0x498F, Data4: ( 0xBA,0x60,0x02,0x89,0xE7,0x6E,0x23,0xDD ) // B5D036D7-E297-498F-BA60-0289E76E23DD
    ) 

}
