// WARNING: Please don't edit this file. It was generated by Swift/WinRT v0.0.1


#pragma once
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wmicrosoft-enum-forward-reference"
#include "test_component.h"
#include "test_component.Delegates.h"
#pragma clang diagnostic pop
