// WARNING: Please don't edit this file. It was generated by Swift/WinRT v0.0.1

#pragma once
// Header files for imported files
#include <inspectable.h>
#include <EventToken.h>
#include <windowscontracts.h>
#include "Windows.Foundation.h"
#include "Microsoft.UI.Xaml.h"
#include "Microsoft.UI.Xaml.Controls.h"

/* Forward Declarations */
// Parameterized interface forward declarations (C)

// Collection interface definitions

#ifndef ____x_ABI_CMicrosoft_CUI_CXaml_CControls_CIAnimatedVisualSource_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CUI_CXaml_CControls_CIAnimatedVisualSource_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CUI_CXaml_CControls_CIAnimatedVisualSource __x_ABI_CMicrosoft_CUI_CXaml_CControls_CIAnimatedVisualSource;

#endif // ____x_ABI_CMicrosoft_CUI_CXaml_CControls_CIAnimatedVisualSource_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CUI_CXaml_CControls_CIAnimatedVisualSource2_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CUI_CXaml_CControls_CIAnimatedVisualSource2_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CUI_CXaml_CControls_CIAnimatedVisualSource2 __x_ABI_CMicrosoft_CUI_CXaml_CControls_CIAnimatedVisualSource2;

#endif // ____x_ABI_CMicrosoft_CUI_CXaml_CControls_CIAnimatedVisualSource2_FWD_DEFINED__

