// WARNING: Please don't edit this file. It was generated by Swift/WinRT v0.0.1

#pragma once
// Header files for imported files
#include <inspectable.h>
#include <EventToken.h>
#include <windowscontracts.h>
#include "Windows.Foundation.h"
#include "Microsoft.UI.Input.h"
#include "Windows.Devices.Input.h"

/* Forward Declarations */
#ifndef ____x_ABI_CMicrosoft_CUI_CInput_CInterop_CIPenDeviceInteropStatics_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CUI_CInput_CInterop_CIPenDeviceInteropStatics_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CUI_CInput_CInterop_CIPenDeviceInteropStatics __x_ABI_CMicrosoft_CUI_CInput_CInterop_CIPenDeviceInteropStatics;

#endif // ____x_ABI_CMicrosoft_CUI_CInput_CInterop_CIPenDeviceInteropStatics_FWD_DEFINED__

// Parameterized interface forward declarations (C)

// Collection interface definitions

#ifndef ____x_ABI_CMicrosoft_CUI_CInput_CIPointerPoint_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CUI_CInput_CIPointerPoint_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CUI_CInput_CIPointerPoint __x_ABI_CMicrosoft_CUI_CInput_CIPointerPoint;

#endif // ____x_ABI_CMicrosoft_CUI_CInput_CIPointerPoint_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CDevices_CInput_CIPenDevice_FWD_DEFINED__
#define ____x_ABI_CWindows_CDevices_CInput_CIPenDevice_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CDevices_CInput_CIPenDevice __x_ABI_CWindows_CDevices_CInput_CIPenDevice;

#endif // ____x_ABI_CWindows_CDevices_CInput_CIPenDevice_FWD_DEFINED__

#if !defined(____x_ABI_CMicrosoft_CUI_CInput_CInterop_CIPenDeviceInteropStatics_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CUI_CInput_CInterop_CIPenDeviceInteropStatics_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CUI_CInput_CInterop_CIPenDeviceInteropStaticsVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CUI_CInput_CInterop_CIPenDeviceInteropStatics* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CUI_CInput_CInterop_CIPenDeviceInteropStatics* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CUI_CInput_CInterop_CIPenDeviceInteropStatics* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CUI_CInput_CInterop_CIPenDeviceInteropStatics* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CUI_CInput_CInterop_CIPenDeviceInteropStatics* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CUI_CInput_CInterop_CIPenDeviceInteropStatics* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* FromPointerPoint)(__x_ABI_CMicrosoft_CUI_CInput_CInterop_CIPenDeviceInteropStatics* This,
        __x_ABI_CMicrosoft_CUI_CInput_CIPointerPoint* pointerPoint,
        __x_ABI_CWindows_CDevices_CInput_CIPenDevice** result);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CUI_CInput_CInterop_CIPenDeviceInteropStaticsVtbl;

    interface __x_ABI_CMicrosoft_CUI_CInput_CInterop_CIPenDeviceInteropStatics
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CUI_CInput_CInterop_CIPenDeviceInteropStaticsVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CUI_CInput_CInterop_CIPenDeviceInteropStatics;
#endif /* !defined(____x_ABI_CMicrosoft_CUI_CInput_CInterop_CIPenDeviceInteropStatics_INTERFACE_DEFINED__) */
    
