// WARNING: Please don't edit this file. It was generated by Swift/WinRT v0.0.1

#pragma once
// Header files for imported files
#include <inspectable.h>
#include <EventToken.h>
#include <windowscontracts.h>
#include "Windows.Foundation.h"
#include "Windows.ApplicationModel.Core.h"
// Importing Collections header
#include "Windows.Foundation.Collections.h"

/* Forward Declarations */
#ifndef ____x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIActivationRegistrationManagerStatics_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIActivationRegistrationManagerStatics_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIActivationRegistrationManagerStatics __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIActivationRegistrationManagerStatics;

#endif // ____x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIActivationRegistrationManagerStatics_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppActivationArguments_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppActivationArguments_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppActivationArguments __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppActivationArguments;

#endif // ____x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppActivationArguments_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstance_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstance_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstance __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstance;

#endif // ____x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstance_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstanceStatics_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstanceStatics_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstanceStatics __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstanceStatics;

#endif // ____x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstanceStatics_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstanceStatics2_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstanceStatics2_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstanceStatics2 __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstanceStatics2;

#endif // ____x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstanceStatics2_FWD_DEFINED__

// Parameterized interface forward declarations (C)

// Collection interface definitions

#if !defined(____x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance __x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance;

    typedef struct __x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstanceVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_Current)(__x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance* This,
        __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstance** result);
    HRESULT (STDMETHODCALLTYPE* get_HasCurrent)(__x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance* This,
        boolean* result);
    HRESULT (STDMETHODCALLTYPE* MoveNext)(__x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance* This,
        boolean* result);
    HRESULT (STDMETHODCALLTYPE* GetMany)(__x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance* This,
        UINT32 itemsLength,
        __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstance** items,
        UINT32* result);

        END_INTERFACE
    } __x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstanceVtbl;

    interface __x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance
    {
        CONST_VTBL struct __x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstanceVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance_INTERFACE_DEFINED__
    
#if !defined(____x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance __x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance;

    typedef struct __x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstanceVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* First)(__x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance* This,
        __x_ABI_C__FIIterator_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance** result);

        END_INTERFACE
    } __x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstanceVtbl;

    interface __x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance
    {
        CONST_VTBL struct __x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstanceVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIIterable_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance_INTERFACE_DEFINED__
    
#if !defined(____x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance __x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance;

    typedef struct __x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstanceVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* GetAt)(__x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance* This,
        UINT32 index,
        __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstance** result);
    HRESULT (STDMETHODCALLTYPE* get_Size)(__x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance* This,
        UINT32* result);
    HRESULT (STDMETHODCALLTYPE* IndexOf)(__x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance* This,
        __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstance* value,
        UINT32* index,
        boolean* result);
    HRESULT (STDMETHODCALLTYPE* GetMany)(__x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance* This,
        UINT32 startIndex,
        UINT32 itemsLength,
        __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstance** items,
        UINT32* result);

        END_INTERFACE
    } __x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstanceVtbl;

    interface __x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance
    {
        CONST_VTBL struct __x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstanceVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance_INTERFACE_DEFINED__
    
#if !defined(____x_ABI_C__FIVector_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIVector_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIVector_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance __x_ABI_C__FIVector_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIVector_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance;

    typedef struct __x_ABI_C__FIVector_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstanceVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIVector_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIVector_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIVector_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_C__FIVector_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_C__FIVector_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_C__FIVector_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* GetAt)(__x_ABI_C__FIVector_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance* This,
        UINT32 index,
        __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstance** result);
    HRESULT (STDMETHODCALLTYPE* get_Size)(__x_ABI_C__FIVector_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance* This,
        UINT32* result);
    HRESULT (STDMETHODCALLTYPE* GetView)(__x_ABI_C__FIVector_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance* This,
        __x_ABI_C__FIVectorView_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance** result);
    HRESULT (STDMETHODCALLTYPE* IndexOf)(__x_ABI_C__FIVector_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance* This,
        __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstance* value,
        UINT32* index,
        boolean* result);
    HRESULT (STDMETHODCALLTYPE* SetAt)(__x_ABI_C__FIVector_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance* This,
        UINT32 index,
        __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstance* value);
    HRESULT (STDMETHODCALLTYPE* InsertAt)(__x_ABI_C__FIVector_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance* This,
        UINT32 index,
        __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstance* value);
    HRESULT (STDMETHODCALLTYPE* RemoveAt)(__x_ABI_C__FIVector_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance* This,
        UINT32 index);
    HRESULT (STDMETHODCALLTYPE* Append)(__x_ABI_C__FIVector_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance* This,
        __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstance* value);
    HRESULT (STDMETHODCALLTYPE* RemoveAtEnd)(__x_ABI_C__FIVector_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance* This);
    HRESULT (STDMETHODCALLTYPE* Clear)(__x_ABI_C__FIVector_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance* This);
    HRESULT (STDMETHODCALLTYPE* GetMany)(__x_ABI_C__FIVector_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance* This,
        UINT32 startIndex,
        UINT32 itemsLength,
        __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstance** items,
        UINT32* result);
    HRESULT (STDMETHODCALLTYPE* ReplaceAll)(__x_ABI_C__FIVector_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance* This,
        UINT32 itemsLength,
        __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstance** items);

        END_INTERFACE
    } __x_ABI_C__FIVector_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstanceVtbl;

    interface __x_ABI_C__FIVector_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance
    {
        CONST_VTBL struct __x_ABI_C__FIVector_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstanceVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIVector_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance_INTERFACE_DEFINED__
    
#if !defined(____x_ABI_C__FIEventHandler_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppActivationArguments_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIEventHandler_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppActivationArguments_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIEventHandler_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppActivationArguments __x_ABI_C__FIEventHandler_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppActivationArguments;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIEventHandler_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppActivationArguments;

    typedef struct __x_ABI_C__FIEventHandler_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppActivationArgumentsVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIEventHandler_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppActivationArguments* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIEventHandler_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppActivationArguments* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIEventHandler_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppActivationArguments* This);
        HRESULT (STDMETHODCALLTYPE* Invoke)(__x_ABI_C__FIEventHandler_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppActivationArguments* This,
        IInspectable* sender,
        __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppActivationArguments* args);

        END_INTERFACE
    } __x_ABI_C__FIEventHandler_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppActivationArgumentsVtbl;

    interface __x_ABI_C__FIEventHandler_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppActivationArguments
    {
        CONST_VTBL struct __x_ABI_C__FIEventHandler_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppActivationArgumentsVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIEventHandler_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppActivationArguments_INTERFACE_DEFINED__
    
typedef enum __x_ABI_CWindows_CApplicationModel_CCore_CAppRestartFailureReason __x_ABI_CWindows_CApplicationModel_CCore_CAppRestartFailureReason;

#ifndef ____x_ABI_CWindows_CFoundation_CIAsyncAction_FWD_DEFINED__
#define ____x_ABI_CWindows_CFoundation_CIAsyncAction_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CFoundation_CIAsyncAction __x_ABI_CWindows_CFoundation_CIAsyncAction;

#endif // ____x_ABI_CWindows_CFoundation_CIAsyncAction_FWD_DEFINED__

typedef enum __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind;

enum __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind
    {
        __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind_Launch = 0,
    __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind_Search = 1,
    __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind_ShareTarget = 2,
    __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind_File = 3,
    __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind_Protocol = 4,
    __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind_FileOpenPicker = 5,
    __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind_FileSavePicker = 6,
    __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind_CachedFileUpdater = 7,
    __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind_ContactPicker = 8,
    __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind_Device = 9,
    __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind_PrintTaskSettings = 10,
    __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind_CameraSettings = 11,
    __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind_RestrictedLaunch = 12,
    __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind_AppointmentsProvider = 13,
    __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind_Contact = 14,
    __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind_LockScreenCall = 15,
    __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind_VoiceCommand = 16,
    __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind_LockScreen = 17,
    __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind_PickerReturned = 1000,
    __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind_WalletAction = 1001,
    __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind_PickFileContinuation = 1002,
    __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind_PickSaveFileContinuation = 1003,
    __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind_PickFolderContinuation = 1004,
    __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind_WebAuthenticationBrokerContinuation = 1005,
    __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind_WebAccountProvider = 1006,
    __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind_ComponentUI = 1007,
    __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind_ProtocolForResults = 1009,
    __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind_ToastNotification = 1010,
    __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind_Print3DWorkflow = 1011,
    __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind_DialReceiver = 1012,
    __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind_DevicePairing = 1013,
    __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind_UserDataAccountsProvider = 1014,
    __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind_FilePickerExperience = 1015,
    __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind_LockScreenComponent = 1016,
    __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind_ContactPanel = 1017,
    __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind_PrintWorkflowForegroundTask = 1018,
    __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind_GameUIProvider = 1019,
    __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind_StartupTask = 1020,
    __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind_CommandLineLaunch = 1021,
    __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind_BarcodeScannerProvider = 1022,
    __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind_PrintSupportJobUI = 1023,
    __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind_PrintSupportSettingsUI = 1024,
    __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind_PhoneCallActivation = 1025,
    __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind_VpnForeground = 1026,
    __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind_Push = 5000,
    __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind_AppNotification = 5001,
};

#if !defined(____x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIActivationRegistrationManagerStatics_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIActivationRegistrationManagerStatics_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIActivationRegistrationManagerStaticsVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIActivationRegistrationManagerStatics* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIActivationRegistrationManagerStatics* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIActivationRegistrationManagerStatics* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIActivationRegistrationManagerStatics* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIActivationRegistrationManagerStatics* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIActivationRegistrationManagerStatics* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* RegisterForFileTypeActivation)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIActivationRegistrationManagerStatics* This,
        UINT32 supportedFileTypesLength,
        HSTRING* supportedFileTypes,
        HSTRING logo,
        HSTRING displayName,
        UINT32 supportedVerbsLength,
        HSTRING* supportedVerbs,
        HSTRING exePath);
    HRESULT (STDMETHODCALLTYPE* RegisterForProtocolActivation)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIActivationRegistrationManagerStatics* This,
        HSTRING scheme,
        HSTRING logo,
        HSTRING displayName,
        HSTRING exePath);
    HRESULT (STDMETHODCALLTYPE* RegisterForStartupActivation)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIActivationRegistrationManagerStatics* This,
        HSTRING taskId,
        HSTRING exePath);
    HRESULT (STDMETHODCALLTYPE* UnregisterForFileTypeActivation)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIActivationRegistrationManagerStatics* This,
        UINT32 fileTypesLength,
        HSTRING* fileTypes,
        HSTRING exePath);
    HRESULT (STDMETHODCALLTYPE* UnregisterForProtocolActivation)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIActivationRegistrationManagerStatics* This,
        HSTRING scheme,
        HSTRING exePath);
    HRESULT (STDMETHODCALLTYPE* UnregisterForStartupActivation)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIActivationRegistrationManagerStatics* This,
        HSTRING taskId);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIActivationRegistrationManagerStaticsVtbl;

    interface __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIActivationRegistrationManagerStatics
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIActivationRegistrationManagerStaticsVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIActivationRegistrationManagerStatics;
#endif /* !defined(____x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIActivationRegistrationManagerStatics_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppActivationArguments_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppActivationArguments_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppActivationArgumentsVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppActivationArguments* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppActivationArguments* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppActivationArguments* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppActivationArguments* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppActivationArguments* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppActivationArguments* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_Kind)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppActivationArguments* This,
        enum __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CExtendedActivationKind* value);
    HRESULT (STDMETHODCALLTYPE* get_Data)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppActivationArguments* This,
        IInspectable** value);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppActivationArgumentsVtbl;

    interface __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppActivationArguments
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppActivationArgumentsVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppActivationArguments;
#endif /* !defined(____x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppActivationArguments_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstance_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstance_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstanceVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstance* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstance* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstance* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstance* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstance* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstance* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* UnregisterKey)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstance* This);
    HRESULT (STDMETHODCALLTYPE* RedirectActivationToAsync)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstance* This,
        __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppActivationArguments* args,
        __x_ABI_CWindows_CFoundation_CIAsyncAction** operation);
    HRESULT (STDMETHODCALLTYPE* GetActivatedEventArgs)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstance* This,
        __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppActivationArguments** result);
    HRESULT (STDMETHODCALLTYPE* add_Activated)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstance* This,
        __x_ABI_C__FIEventHandler_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppActivationArguments* handler,
        EventRegistrationToken* token);
    HRESULT (STDMETHODCALLTYPE* remove_Activated)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstance* This,
        EventRegistrationToken token);
    HRESULT (STDMETHODCALLTYPE* get_Key)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstance* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* get_IsCurrent)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstance* This,
        boolean* value);
    HRESULT (STDMETHODCALLTYPE* get_ProcessId)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstance* This,
        UINT32* value);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstanceVtbl;

    interface __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstance
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstanceVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstance;
#endif /* !defined(____x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstance_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstanceStatics_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstanceStatics_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstanceStaticsVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstanceStatics* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstanceStatics* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstanceStatics* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstanceStatics* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstanceStatics* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstanceStatics* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* GetCurrent)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstanceStatics* This,
        __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstance** result);
    HRESULT (STDMETHODCALLTYPE* GetInstances)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstanceStatics* This,
        __x_ABI_C__FIVector_1___x_ABI_CMicrosoft__CWindows__CAppLifecycle__CAppInstance** result);
    HRESULT (STDMETHODCALLTYPE* FindOrRegisterForKey)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstanceStatics* This,
        HSTRING key,
        __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstance** result);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstanceStaticsVtbl;

    interface __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstanceStatics
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstanceStaticsVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstanceStatics;
#endif /* !defined(____x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstanceStatics_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstanceStatics2_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstanceStatics2_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstanceStatics2Vtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstanceStatics2* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstanceStatics2* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstanceStatics2* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstanceStatics2* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstanceStatics2* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstanceStatics2* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* Restart)(__x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstanceStatics2* This,
        HSTRING arguments,
        enum __x_ABI_CWindows_CApplicationModel_CCore_CAppRestartFailureReason* result);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstanceStatics2Vtbl;

    interface __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstanceStatics2
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstanceStatics2Vtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstanceStatics2;
#endif /* !defined(____x_ABI_CMicrosoft_CWindows_CAppLifecycle_CIAppInstanceStatics2_INTERFACE_DEFINED__) */
    
