// WARNING: Please don't edit this file. It was generated by Swift/WinRT v0.0.1

#pragma once
// Header files for imported files
#include <inspectable.h>
#include <EventToken.h>
#include <windowscontracts.h>
#include "Windows.Foundation.h"
#include "Microsoft.UI.Composition.h"

/* Forward Declarations */
#ifndef ____x_ABI_CMicrosoft_CUI_CComposition_CCore_CICompositorController_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CUI_CComposition_CCore_CICompositorController_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CUI_CComposition_CCore_CICompositorController __x_ABI_CMicrosoft_CUI_CComposition_CCore_CICompositorController;

#endif // ____x_ABI_CMicrosoft_CUI_CComposition_CCore_CICompositorController_FWD_DEFINED__

// Parameterized interface forward declarations (C)

// Collection interface definitions

#if !defined(____x_ABI_C__FITypedEventHandler_2___x_ABI_CMicrosoft__CUI__CComposition__CCore__CCompositorController_IInspectable_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FITypedEventHandler_2___x_ABI_CMicrosoft__CUI__CComposition__CCore__CCompositorController_IInspectable_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FITypedEventHandler_2___x_ABI_CMicrosoft__CUI__CComposition__CCore__CCompositorController_IInspectable __x_ABI_C__FITypedEventHandler_2___x_ABI_CMicrosoft__CUI__CComposition__CCore__CCompositorController_IInspectable;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FITypedEventHandler_2___x_ABI_CMicrosoft__CUI__CComposition__CCore__CCompositorController_IInspectable;

    typedef struct __x_ABI_C__FITypedEventHandler_2___x_ABI_CMicrosoft__CUI__CComposition__CCore__CCompositorController_IInspectableVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FITypedEventHandler_2___x_ABI_CMicrosoft__CUI__CComposition__CCore__CCompositorController_IInspectable* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FITypedEventHandler_2___x_ABI_CMicrosoft__CUI__CComposition__CCore__CCompositorController_IInspectable* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FITypedEventHandler_2___x_ABI_CMicrosoft__CUI__CComposition__CCore__CCompositorController_IInspectable* This);
        HRESULT (STDMETHODCALLTYPE* Invoke)(__x_ABI_C__FITypedEventHandler_2___x_ABI_CMicrosoft__CUI__CComposition__CCore__CCompositorController_IInspectable* This,
        __x_ABI_CMicrosoft_CUI_CComposition_CCore_CICompositorController* sender,
        IInspectable* args);

        END_INTERFACE
    } __x_ABI_C__FITypedEventHandler_2___x_ABI_CMicrosoft__CUI__CComposition__CCore__CCompositorController_IInspectableVtbl;

    interface __x_ABI_C__FITypedEventHandler_2___x_ABI_CMicrosoft__CUI__CComposition__CCore__CCompositorController_IInspectable
    {
        CONST_VTBL struct __x_ABI_C__FITypedEventHandler_2___x_ABI_CMicrosoft__CUI__CComposition__CCore__CCompositorController_IInspectableVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FITypedEventHandler_2___x_ABI_CMicrosoft__CUI__CComposition__CCore__CCompositorController_IInspectable_INTERFACE_DEFINED__
    
#ifndef ____x_ABI_CMicrosoft_CUI_CComposition_CICompositor_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CUI_CComposition_CICompositor_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CUI_CComposition_CICompositor __x_ABI_CMicrosoft_CUI_CComposition_CICompositor;

#endif // ____x_ABI_CMicrosoft_CUI_CComposition_CICompositor_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CFoundation_CIAsyncAction_FWD_DEFINED__
#define ____x_ABI_CWindows_CFoundation_CIAsyncAction_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CFoundation_CIAsyncAction __x_ABI_CWindows_CFoundation_CIAsyncAction;

#endif // ____x_ABI_CWindows_CFoundation_CIAsyncAction_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CFoundation_CIClosable_FWD_DEFINED__
#define ____x_ABI_CWindows_CFoundation_CIClosable_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CFoundation_CIClosable __x_ABI_CWindows_CFoundation_CIClosable;

#endif // ____x_ABI_CWindows_CFoundation_CIClosable_FWD_DEFINED__

#if !defined(____x_ABI_CMicrosoft_CUI_CComposition_CCore_CICompositorController_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CUI_CComposition_CCore_CICompositorController_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CUI_CComposition_CCore_CICompositorControllerVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CUI_CComposition_CCore_CICompositorController* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CUI_CComposition_CCore_CICompositorController* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CUI_CComposition_CCore_CICompositorController* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CUI_CComposition_CCore_CICompositorController* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CUI_CComposition_CCore_CICompositorController* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CUI_CComposition_CCore_CICompositorController* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_Compositor)(__x_ABI_CMicrosoft_CUI_CComposition_CCore_CICompositorController* This,
        __x_ABI_CMicrosoft_CUI_CComposition_CICompositor** value);
    HRESULT (STDMETHODCALLTYPE* Commit)(__x_ABI_CMicrosoft_CUI_CComposition_CCore_CICompositorController* This);
    HRESULT (STDMETHODCALLTYPE* EnsurePreviousCommitCompletedAsync)(__x_ABI_CMicrosoft_CUI_CComposition_CCore_CICompositorController* This,
        __x_ABI_CWindows_CFoundation_CIAsyncAction** operation);
    HRESULT (STDMETHODCALLTYPE* add_CommitNeeded)(__x_ABI_CMicrosoft_CUI_CComposition_CCore_CICompositorController* This,
        __x_ABI_C__FITypedEventHandler_2___x_ABI_CMicrosoft__CUI__CComposition__CCore__CCompositorController_IInspectable* handler,
        EventRegistrationToken* token);
    HRESULT (STDMETHODCALLTYPE* remove_CommitNeeded)(__x_ABI_CMicrosoft_CUI_CComposition_CCore_CICompositorController* This,
        EventRegistrationToken token);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CUI_CComposition_CCore_CICompositorControllerVtbl;

    interface __x_ABI_CMicrosoft_CUI_CComposition_CCore_CICompositorController
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CUI_CComposition_CCore_CICompositorControllerVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CUI_CComposition_CCore_CICompositorController;
#endif /* !defined(____x_ABI_CMicrosoft_CUI_CComposition_CCore_CICompositorController_INTERFACE_DEFINED__) */
    
