// WARNING: Please don't edit this file. It was generated by Swift/WinRT v0.0.1

#pragma once
// Header files for imported files
#include <inspectable.h>
#include <EventToken.h>
#include <windowscontracts.h>
#include "Windows.Foundation.h"
#include "Windows.UI.WindowManagement.h"

/* Forward Declarations */
#ifndef ____x_ABI_CWindows_CUI_CCore_CPreview_CICoreAppWindowPreview_FWD_DEFINED__
#define ____x_ABI_CWindows_CUI_CCore_CPreview_CICoreAppWindowPreview_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CUI_CCore_CPreview_CICoreAppWindowPreview __x_ABI_CWindows_CUI_CCore_CPreview_CICoreAppWindowPreview;

#endif // ____x_ABI_CWindows_CUI_CCore_CPreview_CICoreAppWindowPreview_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CUI_CCore_CPreview_CICoreAppWindowPreviewStatics_FWD_DEFINED__
#define ____x_ABI_CWindows_CUI_CCore_CPreview_CICoreAppWindowPreviewStatics_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CUI_CCore_CPreview_CICoreAppWindowPreviewStatics __x_ABI_CWindows_CUI_CCore_CPreview_CICoreAppWindowPreviewStatics;

#endif // ____x_ABI_CWindows_CUI_CCore_CPreview_CICoreAppWindowPreviewStatics_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationCloseRequestedPreviewEventArgs_FWD_DEFINED__
#define ____x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationCloseRequestedPreviewEventArgs_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationCloseRequestedPreviewEventArgs __x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationCloseRequestedPreviewEventArgs;

#endif // ____x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationCloseRequestedPreviewEventArgs_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationManagerPreview_FWD_DEFINED__
#define ____x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationManagerPreview_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationManagerPreview __x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationManagerPreview;

#endif // ____x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationManagerPreview_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationManagerPreviewStatics_FWD_DEFINED__
#define ____x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationManagerPreviewStatics_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationManagerPreviewStatics __x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationManagerPreviewStatics;

#endif // ____x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationManagerPreviewStatics_FWD_DEFINED__

// Parameterized interface forward declarations (C)

// Collection interface definitions

#if !defined(____x_ABI_C__FIEventHandler_1___x_ABI_CWindows__CUI__CCore__CPreview__CSystemNavigationCloseRequestedPreviewEventArgs_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIEventHandler_1___x_ABI_CWindows__CUI__CCore__CPreview__CSystemNavigationCloseRequestedPreviewEventArgs_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIEventHandler_1___x_ABI_CWindows__CUI__CCore__CPreview__CSystemNavigationCloseRequestedPreviewEventArgs __x_ABI_C__FIEventHandler_1___x_ABI_CWindows__CUI__CCore__CPreview__CSystemNavigationCloseRequestedPreviewEventArgs;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIEventHandler_1___x_ABI_CWindows__CUI__CCore__CPreview__CSystemNavigationCloseRequestedPreviewEventArgs;

    typedef struct __x_ABI_C__FIEventHandler_1___x_ABI_CWindows__CUI__CCore__CPreview__CSystemNavigationCloseRequestedPreviewEventArgsVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIEventHandler_1___x_ABI_CWindows__CUI__CCore__CPreview__CSystemNavigationCloseRequestedPreviewEventArgs* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIEventHandler_1___x_ABI_CWindows__CUI__CCore__CPreview__CSystemNavigationCloseRequestedPreviewEventArgs* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIEventHandler_1___x_ABI_CWindows__CUI__CCore__CPreview__CSystemNavigationCloseRequestedPreviewEventArgs* This);
        HRESULT (STDMETHODCALLTYPE* Invoke)(__x_ABI_C__FIEventHandler_1___x_ABI_CWindows__CUI__CCore__CPreview__CSystemNavigationCloseRequestedPreviewEventArgs* This,
        IInspectable* sender,
        __x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationCloseRequestedPreviewEventArgs* args);

        END_INTERFACE
    } __x_ABI_C__FIEventHandler_1___x_ABI_CWindows__CUI__CCore__CPreview__CSystemNavigationCloseRequestedPreviewEventArgsVtbl;

    interface __x_ABI_C__FIEventHandler_1___x_ABI_CWindows__CUI__CCore__CPreview__CSystemNavigationCloseRequestedPreviewEventArgs
    {
        CONST_VTBL struct __x_ABI_C__FIEventHandler_1___x_ABI_CWindows__CUI__CCore__CPreview__CSystemNavigationCloseRequestedPreviewEventArgsVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIEventHandler_1___x_ABI_CWindows__CUI__CCore__CPreview__CSystemNavigationCloseRequestedPreviewEventArgs_INTERFACE_DEFINED__
    
#ifndef ____x_ABI_CWindows_CFoundation_CIDeferral_FWD_DEFINED__
#define ____x_ABI_CWindows_CFoundation_CIDeferral_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CFoundation_CIDeferral __x_ABI_CWindows_CFoundation_CIDeferral;

#endif // ____x_ABI_CWindows_CFoundation_CIDeferral_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CUI_CWindowManagement_CIAppWindow_FWD_DEFINED__
#define ____x_ABI_CWindows_CUI_CWindowManagement_CIAppWindow_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CUI_CWindowManagement_CIAppWindow __x_ABI_CWindows_CUI_CWindowManagement_CIAppWindow;

#endif // ____x_ABI_CWindows_CUI_CWindowManagement_CIAppWindow_FWD_DEFINED__

#if !defined(____x_ABI_CWindows_CUI_CCore_CPreview_CICoreAppWindowPreview_INTERFACE_DEFINED__)
    #define ____x_ABI_CWindows_CUI_CCore_CPreview_CICoreAppWindowPreview_INTERFACE_DEFINED__
    typedef struct __x_ABI_CWindows_CUI_CCore_CPreview_CICoreAppWindowPreviewVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CWindows_CUI_CCore_CPreview_CICoreAppWindowPreview* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CWindows_CUI_CCore_CPreview_CICoreAppWindowPreview* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CWindows_CUI_CCore_CPreview_CICoreAppWindowPreview* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CWindows_CUI_CCore_CPreview_CICoreAppWindowPreview* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CWindows_CUI_CCore_CPreview_CICoreAppWindowPreview* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CWindows_CUI_CCore_CPreview_CICoreAppWindowPreview* This,
            TrustLevel* trustLevel);
    
        END_INTERFACE
    } __x_ABI_CWindows_CUI_CCore_CPreview_CICoreAppWindowPreviewVtbl;

    interface __x_ABI_CWindows_CUI_CCore_CPreview_CICoreAppWindowPreview
    {
        CONST_VTBL struct __x_ABI_CWindows_CUI_CCore_CPreview_CICoreAppWindowPreviewVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CWindows_CUI_CCore_CPreview_CICoreAppWindowPreview;
#endif /* !defined(____x_ABI_CWindows_CUI_CCore_CPreview_CICoreAppWindowPreview_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CWindows_CUI_CCore_CPreview_CICoreAppWindowPreviewStatics_INTERFACE_DEFINED__)
    #define ____x_ABI_CWindows_CUI_CCore_CPreview_CICoreAppWindowPreviewStatics_INTERFACE_DEFINED__
    typedef struct __x_ABI_CWindows_CUI_CCore_CPreview_CICoreAppWindowPreviewStaticsVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CWindows_CUI_CCore_CPreview_CICoreAppWindowPreviewStatics* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CWindows_CUI_CCore_CPreview_CICoreAppWindowPreviewStatics* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CWindows_CUI_CCore_CPreview_CICoreAppWindowPreviewStatics* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CWindows_CUI_CCore_CPreview_CICoreAppWindowPreviewStatics* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CWindows_CUI_CCore_CPreview_CICoreAppWindowPreviewStatics* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CWindows_CUI_CCore_CPreview_CICoreAppWindowPreviewStatics* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* GetIdFromWindow)(__x_ABI_CWindows_CUI_CCore_CPreview_CICoreAppWindowPreviewStatics* This,
        __x_ABI_CWindows_CUI_CWindowManagement_CIAppWindow* window,
        INT32* result);

        END_INTERFACE
    } __x_ABI_CWindows_CUI_CCore_CPreview_CICoreAppWindowPreviewStaticsVtbl;

    interface __x_ABI_CWindows_CUI_CCore_CPreview_CICoreAppWindowPreviewStatics
    {
        CONST_VTBL struct __x_ABI_CWindows_CUI_CCore_CPreview_CICoreAppWindowPreviewStaticsVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CWindows_CUI_CCore_CPreview_CICoreAppWindowPreviewStatics;
#endif /* !defined(____x_ABI_CWindows_CUI_CCore_CPreview_CICoreAppWindowPreviewStatics_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationCloseRequestedPreviewEventArgs_INTERFACE_DEFINED__)
    #define ____x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationCloseRequestedPreviewEventArgs_INTERFACE_DEFINED__
    typedef struct __x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationCloseRequestedPreviewEventArgsVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationCloseRequestedPreviewEventArgs* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationCloseRequestedPreviewEventArgs* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationCloseRequestedPreviewEventArgs* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationCloseRequestedPreviewEventArgs* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationCloseRequestedPreviewEventArgs* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationCloseRequestedPreviewEventArgs* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_Handled)(__x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationCloseRequestedPreviewEventArgs* This,
        boolean* value);
    HRESULT (STDMETHODCALLTYPE* put_Handled)(__x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationCloseRequestedPreviewEventArgs* This,
        boolean value);
    HRESULT (STDMETHODCALLTYPE* GetDeferral)(__x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationCloseRequestedPreviewEventArgs* This,
        __x_ABI_CWindows_CFoundation_CIDeferral** result);

        END_INTERFACE
    } __x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationCloseRequestedPreviewEventArgsVtbl;

    interface __x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationCloseRequestedPreviewEventArgs
    {
        CONST_VTBL struct __x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationCloseRequestedPreviewEventArgsVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationCloseRequestedPreviewEventArgs;
#endif /* !defined(____x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationCloseRequestedPreviewEventArgs_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationManagerPreview_INTERFACE_DEFINED__)
    #define ____x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationManagerPreview_INTERFACE_DEFINED__
    typedef struct __x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationManagerPreviewVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationManagerPreview* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationManagerPreview* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationManagerPreview* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationManagerPreview* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationManagerPreview* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationManagerPreview* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* add_CloseRequested)(__x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationManagerPreview* This,
        __x_ABI_C__FIEventHandler_1___x_ABI_CWindows__CUI__CCore__CPreview__CSystemNavigationCloseRequestedPreviewEventArgs* handler,
        EventRegistrationToken* token);
    HRESULT (STDMETHODCALLTYPE* remove_CloseRequested)(__x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationManagerPreview* This,
        EventRegistrationToken token);

        END_INTERFACE
    } __x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationManagerPreviewVtbl;

    interface __x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationManagerPreview
    {
        CONST_VTBL struct __x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationManagerPreviewVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationManagerPreview;
#endif /* !defined(____x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationManagerPreview_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationManagerPreviewStatics_INTERFACE_DEFINED__)
    #define ____x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationManagerPreviewStatics_INTERFACE_DEFINED__
    typedef struct __x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationManagerPreviewStaticsVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationManagerPreviewStatics* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationManagerPreviewStatics* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationManagerPreviewStatics* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationManagerPreviewStatics* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationManagerPreviewStatics* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationManagerPreviewStatics* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* GetForCurrentView)(__x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationManagerPreviewStatics* This,
        __x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationManagerPreview** loader);

        END_INTERFACE
    } __x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationManagerPreviewStaticsVtbl;

    interface __x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationManagerPreviewStatics
    {
        CONST_VTBL struct __x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationManagerPreviewStaticsVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationManagerPreviewStatics;
#endif /* !defined(____x_ABI_CWindows_CUI_CCore_CPreview_CISystemNavigationManagerPreviewStatics_INTERFACE_DEFINED__) */
    
