// WARNING: Please don't edit this file. It was generated by Swift/WinRT v0.0.1

#pragma once
// Header files for imported files
#include <inspectable.h>
#include <EventToken.h>
#include <windowscontracts.h>
#include "Windows.Foundation.h"

/* Forward Declarations */
#ifndef ____x_ABI_CWindows_CPhone_CDevices_CPower_CIBattery_FWD_DEFINED__
#define ____x_ABI_CWindows_CPhone_CDevices_CPower_CIBattery_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CPhone_CDevices_CPower_CIBattery __x_ABI_CWindows_CPhone_CDevices_CPower_CIBattery;

#endif // ____x_ABI_CWindows_CPhone_CDevices_CPower_CIBattery_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CPhone_CDevices_CPower_CIBatteryStatics_FWD_DEFINED__
#define ____x_ABI_CWindows_CPhone_CDevices_CPower_CIBatteryStatics_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CPhone_CDevices_CPower_CIBatteryStatics __x_ABI_CWindows_CPhone_CDevices_CPower_CIBatteryStatics;

#endif // ____x_ABI_CWindows_CPhone_CDevices_CPower_CIBatteryStatics_FWD_DEFINED__

// Parameterized interface forward declarations (C)

// Collection interface definitions

#if !defined(____x_ABI_C__FIEventHandler_1_IInspectable_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIEventHandler_1_IInspectable_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIEventHandler_1_IInspectable __x_ABI_C__FIEventHandler_1_IInspectable;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIEventHandler_1_IInspectable;

    typedef struct __x_ABI_C__FIEventHandler_1_IInspectableVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIEventHandler_1_IInspectable* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIEventHandler_1_IInspectable* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIEventHandler_1_IInspectable* This);
        HRESULT (STDMETHODCALLTYPE* Invoke)(__x_ABI_C__FIEventHandler_1_IInspectable* This,
        IInspectable* sender,
        IInspectable* args);

        END_INTERFACE
    } __x_ABI_C__FIEventHandler_1_IInspectableVtbl;

    interface __x_ABI_C__FIEventHandler_1_IInspectable
    {
        CONST_VTBL struct __x_ABI_C__FIEventHandler_1_IInspectableVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIEventHandler_1_IInspectable_INTERFACE_DEFINED__
    
typedef struct __x_ABI_CWindows_CFoundation_CTimeSpan __x_ABI_CWindows_CFoundation_CTimeSpan;

#if !defined(____x_ABI_CWindows_CPhone_CDevices_CPower_CIBattery_INTERFACE_DEFINED__)
    #define ____x_ABI_CWindows_CPhone_CDevices_CPower_CIBattery_INTERFACE_DEFINED__
    typedef struct __x_ABI_CWindows_CPhone_CDevices_CPower_CIBatteryVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CWindows_CPhone_CDevices_CPower_CIBattery* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CWindows_CPhone_CDevices_CPower_CIBattery* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CWindows_CPhone_CDevices_CPower_CIBattery* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CWindows_CPhone_CDevices_CPower_CIBattery* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CWindows_CPhone_CDevices_CPower_CIBattery* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CWindows_CPhone_CDevices_CPower_CIBattery* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_RemainingChargePercent)(__x_ABI_CWindows_CPhone_CDevices_CPower_CIBattery* This,
        INT32* value);
    HRESULT (STDMETHODCALLTYPE* get_RemainingDischargeTime)(__x_ABI_CWindows_CPhone_CDevices_CPower_CIBattery* This,
        struct __x_ABI_CWindows_CFoundation_CTimeSpan* value);
    HRESULT (STDMETHODCALLTYPE* add_RemainingChargePercentChanged)(__x_ABI_CWindows_CPhone_CDevices_CPower_CIBattery* This,
        __x_ABI_C__FIEventHandler_1_IInspectable* changeHandler,
        EventRegistrationToken* token);
    HRESULT (STDMETHODCALLTYPE* remove_RemainingChargePercentChanged)(__x_ABI_CWindows_CPhone_CDevices_CPower_CIBattery* This,
        EventRegistrationToken token);

        END_INTERFACE
    } __x_ABI_CWindows_CPhone_CDevices_CPower_CIBatteryVtbl;

    interface __x_ABI_CWindows_CPhone_CDevices_CPower_CIBattery
    {
        CONST_VTBL struct __x_ABI_CWindows_CPhone_CDevices_CPower_CIBatteryVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CWindows_CPhone_CDevices_CPower_CIBattery;
#endif /* !defined(____x_ABI_CWindows_CPhone_CDevices_CPower_CIBattery_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CWindows_CPhone_CDevices_CPower_CIBatteryStatics_INTERFACE_DEFINED__)
    #define ____x_ABI_CWindows_CPhone_CDevices_CPower_CIBatteryStatics_INTERFACE_DEFINED__
    typedef struct __x_ABI_CWindows_CPhone_CDevices_CPower_CIBatteryStaticsVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CWindows_CPhone_CDevices_CPower_CIBatteryStatics* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CWindows_CPhone_CDevices_CPower_CIBatteryStatics* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CWindows_CPhone_CDevices_CPower_CIBatteryStatics* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CWindows_CPhone_CDevices_CPower_CIBatteryStatics* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CWindows_CPhone_CDevices_CPower_CIBatteryStatics* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CWindows_CPhone_CDevices_CPower_CIBatteryStatics* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* GetDefault)(__x_ABI_CWindows_CPhone_CDevices_CPower_CIBatteryStatics* This,
        __x_ABI_CWindows_CPhone_CDevices_CPower_CIBattery** result);

        END_INTERFACE
    } __x_ABI_CWindows_CPhone_CDevices_CPower_CIBatteryStaticsVtbl;

    interface __x_ABI_CWindows_CPhone_CDevices_CPower_CIBatteryStatics
    {
        CONST_VTBL struct __x_ABI_CWindows_CPhone_CDevices_CPower_CIBatteryStaticsVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CWindows_CPhone_CDevices_CPower_CIBatteryStatics;
#endif /* !defined(____x_ABI_CWindows_CPhone_CDevices_CPower_CIBatteryStatics_INTERFACE_DEFINED__) */
    
