// WARNING: Please don't edit this file. It was generated by Swift/WinRT v0.0.1

#pragma once
// Header files for imported files
#include <inspectable.h>
#include <EventToken.h>
#include <windowscontracts.h>
#include "Windows.Foundation.h"
#include "Windows.UI.h"

/* Forward Declarations */
#ifndef ____x_ABI_CWindows_CMedia_CClosedCaptioning_CIClosedCaptionPropertiesStatics_FWD_DEFINED__
#define ____x_ABI_CWindows_CMedia_CClosedCaptioning_CIClosedCaptionPropertiesStatics_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CMedia_CClosedCaptioning_CIClosedCaptionPropertiesStatics __x_ABI_CWindows_CMedia_CClosedCaptioning_CIClosedCaptionPropertiesStatics;

#endif // ____x_ABI_CWindows_CMedia_CClosedCaptioning_CIClosedCaptionPropertiesStatics_FWD_DEFINED__

// Parameterized interface forward declarations (C)

// Collection interface definitions

typedef struct __x_ABI_CWindows_CUI_CColor __x_ABI_CWindows_CUI_CColor;

typedef enum __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionColor __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionColor;

typedef enum __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionEdgeEffect __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionEdgeEffect;

typedef enum __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionOpacity __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionOpacity;

typedef enum __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionSize __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionSize;

typedef enum __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionStyle __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionStyle;

enum __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionColor
    {
        __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionColor_Default = 0,
    __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionColor_White = 1,
    __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionColor_Black = 2,
    __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionColor_Red = 3,
    __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionColor_Green = 4,
    __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionColor_Blue = 5,
    __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionColor_Yellow = 6,
    __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionColor_Magenta = 7,
    __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionColor_Cyan = 8,
};

enum __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionEdgeEffect
    {
        __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionEdgeEffect_Default = 0,
    __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionEdgeEffect_None = 1,
    __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionEdgeEffect_Raised = 2,
    __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionEdgeEffect_Depressed = 3,
    __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionEdgeEffect_Uniform = 4,
    __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionEdgeEffect_DropShadow = 5,
};

enum __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionOpacity
    {
        __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionOpacity_Default = 0,
    __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionOpacity_OneHundredPercent = 1,
    __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionOpacity_SeventyFivePercent = 2,
    __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionOpacity_TwentyFivePercent = 3,
    __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionOpacity_ZeroPercent = 4,
};

enum __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionSize
    {
        __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionSize_Default = 0,
    __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionSize_FiftyPercent = 1,
    __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionSize_OneHundredPercent = 2,
    __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionSize_OneHundredFiftyPercent = 3,
    __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionSize_TwoHundredPercent = 4,
};

enum __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionStyle
    {
        __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionStyle_Default = 0,
    __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionStyle_MonospacedWithSerifs = 1,
    __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionStyle_ProportionalWithSerifs = 2,
    __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionStyle_MonospacedWithoutSerifs = 3,
    __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionStyle_ProportionalWithoutSerifs = 4,
    __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionStyle_Casual = 5,
    __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionStyle_Cursive = 6,
    __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionStyle_SmallCapitals = 7,
};

#if !defined(____x_ABI_CWindows_CMedia_CClosedCaptioning_CIClosedCaptionPropertiesStatics_INTERFACE_DEFINED__)
    #define ____x_ABI_CWindows_CMedia_CClosedCaptioning_CIClosedCaptionPropertiesStatics_INTERFACE_DEFINED__
    typedef struct __x_ABI_CWindows_CMedia_CClosedCaptioning_CIClosedCaptionPropertiesStaticsVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CWindows_CMedia_CClosedCaptioning_CIClosedCaptionPropertiesStatics* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CWindows_CMedia_CClosedCaptioning_CIClosedCaptionPropertiesStatics* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CWindows_CMedia_CClosedCaptioning_CIClosedCaptionPropertiesStatics* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CWindows_CMedia_CClosedCaptioning_CIClosedCaptionPropertiesStatics* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CWindows_CMedia_CClosedCaptioning_CIClosedCaptionPropertiesStatics* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CWindows_CMedia_CClosedCaptioning_CIClosedCaptionPropertiesStatics* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_FontColor)(__x_ABI_CWindows_CMedia_CClosedCaptioning_CIClosedCaptionPropertiesStatics* This,
        enum __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionColor* value);
    HRESULT (STDMETHODCALLTYPE* get_ComputedFontColor)(__x_ABI_CWindows_CMedia_CClosedCaptioning_CIClosedCaptionPropertiesStatics* This,
        struct __x_ABI_CWindows_CUI_CColor* value);
    HRESULT (STDMETHODCALLTYPE* get_FontOpacity)(__x_ABI_CWindows_CMedia_CClosedCaptioning_CIClosedCaptionPropertiesStatics* This,
        enum __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionOpacity* value);
    HRESULT (STDMETHODCALLTYPE* get_FontSize)(__x_ABI_CWindows_CMedia_CClosedCaptioning_CIClosedCaptionPropertiesStatics* This,
        enum __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionSize* value);
    HRESULT (STDMETHODCALLTYPE* get_FontStyle)(__x_ABI_CWindows_CMedia_CClosedCaptioning_CIClosedCaptionPropertiesStatics* This,
        enum __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionStyle* value);
    HRESULT (STDMETHODCALLTYPE* get_FontEffect)(__x_ABI_CWindows_CMedia_CClosedCaptioning_CIClosedCaptionPropertiesStatics* This,
        enum __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionEdgeEffect* value);
    HRESULT (STDMETHODCALLTYPE* get_BackgroundColor)(__x_ABI_CWindows_CMedia_CClosedCaptioning_CIClosedCaptionPropertiesStatics* This,
        enum __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionColor* value);
    HRESULT (STDMETHODCALLTYPE* get_ComputedBackgroundColor)(__x_ABI_CWindows_CMedia_CClosedCaptioning_CIClosedCaptionPropertiesStatics* This,
        struct __x_ABI_CWindows_CUI_CColor* value);
    HRESULT (STDMETHODCALLTYPE* get_BackgroundOpacity)(__x_ABI_CWindows_CMedia_CClosedCaptioning_CIClosedCaptionPropertiesStatics* This,
        enum __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionOpacity* value);
    HRESULT (STDMETHODCALLTYPE* get_RegionColor)(__x_ABI_CWindows_CMedia_CClosedCaptioning_CIClosedCaptionPropertiesStatics* This,
        enum __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionColor* value);
    HRESULT (STDMETHODCALLTYPE* get_ComputedRegionColor)(__x_ABI_CWindows_CMedia_CClosedCaptioning_CIClosedCaptionPropertiesStatics* This,
        struct __x_ABI_CWindows_CUI_CColor* value);
    HRESULT (STDMETHODCALLTYPE* get_RegionOpacity)(__x_ABI_CWindows_CMedia_CClosedCaptioning_CIClosedCaptionPropertiesStatics* This,
        enum __x_ABI_CWindows_CMedia_CClosedCaptioning_CClosedCaptionOpacity* value);

        END_INTERFACE
    } __x_ABI_CWindows_CMedia_CClosedCaptioning_CIClosedCaptionPropertiesStaticsVtbl;

    interface __x_ABI_CWindows_CMedia_CClosedCaptioning_CIClosedCaptionPropertiesStatics
    {
        CONST_VTBL struct __x_ABI_CWindows_CMedia_CClosedCaptioning_CIClosedCaptionPropertiesStaticsVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CWindows_CMedia_CClosedCaptioning_CIClosedCaptionPropertiesStatics;
#endif /* !defined(____x_ABI_CWindows_CMedia_CClosedCaptioning_CIClosedCaptionPropertiesStatics_INTERFACE_DEFINED__) */
    
