// WARNING: Please don't edit this file. It was generated by Swift/WinRT v0.0.1
// swiftlint:disable all
import Foundation
import CUWP
@_spi(WinRTInternal) @_spi(WinRTImplements) import WindowsFoundation
import CWindowsFoundation
import CWinRT

/// [Open Microsoft documentation](https://learn.microsoft.com/uwp/api/windows.storage.storagedeleteoption)
public typealias StorageDeleteOption = __x_ABI_CWindows_CStorage_CStorageDeleteOption

extension UWP.StorageDeleteOption {
    public static var `default` : UWP.StorageDeleteOption {
        __x_ABI_CWindows_CStorage_CStorageDeleteOption_Default
    }
    public static var permanentDelete : UWP.StorageDeleteOption {
        __x_ABI_CWindows_CStorage_CStorageDeleteOption_PermanentDelete
    }
}
extension UWP.StorageDeleteOption: @retroactive Hashable, @retroactive Codable, @retroactive @unchecked Sendable {}

