// WARNING: Please don't edit this file. It was generated by Swift/WinRT v0.0.1
// swiftlint:disable all
import Foundation
@_spi(WinRTInternal) @_spi(WinRTImplements) import WindowsFoundation
import CWinRT

/// [Open Microsoft documentation](https://learn.microsoft.com/uwp/api/windows.storage.fileaccessmode)
public typealias FileAccessMode = __x_ABI_CWindows_CStorage_CFileAccessMode

extension UWP.FileAccessMode {
    public static var read : UWP.FileAccessMode {
        __x_ABI_CWindows_CStorage_CFileAccessMode_Read
    }
    public static var readWrite : UWP.FileAccessMode {
        __x_ABI_CWindows_CStorage_CFileAccessMode_ReadWrite
    }
}
extension UWP.FileAccessMode: @retroactive Hashable, @retroactive Codable, @retroactive @unchecked Sendable {}

