#pragma once

#include "types/metadata_type.h"
#include "types/type_constants.h"
#include "types/generic_type_parameter.h"
#include "types/element_type.h"
#include "types/system_type.h"
#include "types/mapped_type.h"
#include "types/typedef_base.h"
#include "types/enum_type.h"
#include "types/struct_member.h"
#include "types/struct_type.h"
#include "types/function_return_type.h"
#include "types/function_param.h"
#include "types/function_def.h"
#include "types/property_def.h"
#include "types/event_def.h"
#include "types/interface_info.h"
#include "types/attributed_type.h"
#include "types/delegate_type.h"
#include "types/interface_type.h"
#include "types/class_type.h"
#include "types/generic_inst.h"
#include "types/type_traits.h"

