// WARNING: Please don't edit this file. It was generated by Swift/WinRT v0.0.1
// swiftlint:disable all
import Foundation
import Ctest_component

/// [Open Microsoft documentation](https://learn.microsoft.com/uwp/api/windows.system.userauthenticationstatus)
public typealias UserAuthenticationStatus = __x_ABI_CWindows_CSystem_CUserAuthenticationStatus

extension test_component.UserAuthenticationStatus {
    public static var unauthenticated : test_component.UserAuthenticationStatus {
        __x_ABI_CWindows_CSystem_CUserAuthenticationStatus_Unauthenticated
    }
    public static var locallyAuthenticated : test_component.UserAuthenticationStatus {
        __x_ABI_CWindows_CSystem_CUserAuthenticationStatus_LocallyAuthenticated
    }
    public static var remotelyAuthenticated : test_component.UserAuthenticationStatus {
        __x_ABI_CWindows_CSystem_CUserAuthenticationStatus_RemotelyAuthenticated
    }
}
extension test_component.UserAuthenticationStatus: @retroactive Hashable, @retroactive Codable, @retroactive @unchecked Sendable {}

