name: Build for Nuget.org

on:
  workflow_dispatch:

jobs:
  release-and-publish:
    name: Swift/WinRT Release Build
    secrets: inherit
    uses: ./.github/workflows/callable-windows-build.yml
    with:
      config: release
      publish-nuget: true
      nuget-version: 0.${{ github.run_number }}.0
